### ISSUE TITLE
[SENTRY] EAI_AGAIN error

### ISSUE THREAD

**Issue by conrad-vanl** [NewSpring/Apollos#489]
I believe this happens during the checkout process after payment sometimes. I believe that Isaac mentioned that it's related to the beta rock environment, but I'd like confirmation.

https://sentry.io/newspring-church/app/issues/523703403/

```
Error: GraphQL error: Int cannot represent non 32-bit signed integer value: EAI_AGAIN
  at ApolloError (../node_modules/apollo-client/errors/ApolloError.js:43:1)
  at call (../node_modules/apollo-client/core/QueryManager.js:103:1)
  at next (../node_modules/zen-observable/zen-observable.js:158:1)
  at call (../node_modules/apollo-link-error/lib/index.js:26:1)
  at next (../node_modules/zen-observable/zen-observable.js:158:1)
...
(4 additional frame(s) were not displayed)
```

**Comment by cdanwards** [comment]
@IsaacHardy EAI_AGAIN is also being thrown in the error in #486
