### ISSUE TITLE
TypeError: TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(a,e.prototype)')

### ISSUE THREAD

**Issue by burkeshartsis** [NewSpring/Apollos#496]
Steps to reproduce:
1. open app and navigate to "Sections Menu"
2. turn on Airplane mode (lose data connection)
3. tap "Give"
4. crash

This is reproducible locally as well pointing at the local packager. @IsaacHardy says it's Android specific. 

https://sentry.io/newspring-church/app/issues/525489396/

```
TypeError: TypeError: undefined is not a function (evaluating 'Object.setPrototypeOf(a,e.prototype)')

This error is located at:
    in e
    in Apollo(Component)
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in n
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in n
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in n
    in Unknown
    in Unknown
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in e
    in e
    in e
    in RCTView
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in n
    in Unknown
    in Unknown
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in t
    in r
    in u
    in Unknown
    in e
    in RCTView
    in n
    in Unknown
    in e
    in Unknown
    in RCTView
    in t
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in e
    in withRouter()
    in Unknown
    in RCTView
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in n
    in Unknown
    in e
    in Unknown
    in RCTView
    in t
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in e
    in withRouter()
    in Unknown
    in RCTView
    in n
    in t
    in r
    in e
    in Apollo(r)
    in e
    in Apollo(Apollo(r))
    in e
    in Apollo(Apollo(Apollo(r)))
    in e
    in Apollo(Apollo(Apollo(Apollo(r))))
    in e
    in Apollo(Apollo(Apollo(Apollo(Apollo(r)))))
    in e
    in Apollo(Apollo(Apollo(Apollo(Apollo(Apollo(r))))))
    in e
    in Apollo(Apollo(Apollo(Apollo(Apollo(Apollo(Apollo(r)))))))
    in e
    in withRouter(Apollo(Apollo(Apollo(Apollo(Apollo(Apollo(Apollo(r))))))))
    in RCTView
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in t
    in Unknown
    in Unknown
    in Unknown
    in n
    in e
    in withRouter(n)
    in e
    in t
    in Unknown
    in RCTView
    in Unknown
    in r
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in e
    in Apollo(Component)
    in e
    in Apollo(Apollo(Component))
    in e
    in Apollo(Apollo(Apollo(Component)))
    in Unknown
    in e
    in Apollo(Component)
    in RCTView
    in t
    in t
    in t
    in t
    in e
    in Unknown
    in Unknown
    in r
    in RCTView
    in RCTView
    in t
  at finished (/Volumes/Makers/Sites/Apollos/src/@ui/CardStack/Transitioner.js:345:3)
  at None (/Volumes/Makers/Sites/Apollos/src/@ui/CardStack/Transitioner.js:210:17)
  at None ([native code])
...
(20 additional frame(s) were not displayed)
```

**Comment by IsaacHardy** [comment]
@conrad-vanl Should this issue be closed?
