### ISSUE TITLE
Series with no sermons loads forever

### ISSUE THREAD

**Issue by johnthepink** [NewSpring/Apollos#858]
If the current series has no sermons, it displays a loading symbol indefinitely.

**Comment by johnthepink** [comment]
@jbaxleyiii maybe you knew this, but there is a GraphQL error involved with this

```
TypeError: data.map is not a function
    at Content._callee3$ (model.js:28:37)
    at tryCatch (/src/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/src/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/src/node_modules/regenerator-runtime/runtime.js:95:21)
    at model.js:6:65
    at new Promise (/src/node_modules/core-js/modules/es6.promise.js:191:7)
    at Promise.exports.(anonymous function).target.(anonymous function).function.target.(anonymous function).F (/src/node_modules/core-js/library/modules/_export.js:35:28)
    at __awaiter (model.js:2:12)
    at Content.getFromIds (model.js:27:16)
    at run (/src/node_modules/core-js/modules/es6.promise.js:87:22)
    at /src/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/src/node_modules/core-js/modules/_microtask.js:18:9)
    at wrapped (/src/node_modules/newrelic/lib/transaction/tracer/index.js:161:28)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at process.wrappedFunction (/src/node_modules/newrelic/lib/transaction/tracer/index.js:257:51)
```

**Comment by johnthepink** [comment]
i'm going to fix it on the client side, and file an issue on heighliner
